### ISSUE TITLE
get_apitoken函数请求失败，返回错误数据

### ISSUE THREAD

**Issue by DiyaDe** [huajien/ZXJY_DK#23]
报错内容如下：
Traceback (most recent call last):
  File "E:\Program Files\PyCharm 2023.3.5\plugins\python\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\Program Files\PyCharm 2023.3.5\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\33323\Downloads\ZXJY_DK-master\parsUserConfig.py", line 62, in <module>
    main.main()
  File "C:\Users\33323\Downloads\ZXJY_DK-master\main.py", line 26, in main
    winmain(AllUsers)
  File "C:\Users\33323\Downloads\ZXJY_DK-master\main.py", line 9, in winmain
    parsUserConfig.LoadUserConfig(user)
  File "C:\Users\33323\Downloads\ZXJY_DK-master\parsUserConfig.py", line 20, in LoadUserConfig
    getApiState, getApiToken = apitoken.get_apitoken()
ValueError: too many values to unpack (expected 2)
原因貌似是，服务器拒绝连接，报错如下：
requests.exceptions.SSLError: HTTPSConnectionPool(host='sxbaapp.zcj.jyt.henan.gov.cn', port=443): Max retries exceeded with url: /api/getApitoken.ashx (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))

**Comment by siYH0** [comment]
职校家园后台域名换了，替换之前的使用https://sxbaapp.dxtxl.com

**Comment by huajien** [comment]
好的晚会我看一下

**Comment by QQBBER** [comment]
大佬手机版的，打不了卡了

**Comment by huajien** [comment]
> 大佬手机版的，打不了卡了

我抽空更新一下，我这个电脑没有安卓开发环境，抱歉

**Comment by huajien** [comment]
> 大佬手机版的，打不了卡了

已经更新了[手机版本1.0.1](https://github.com/huajien/ZXJY_DK/releases/download/1.0.1/1.0.1.apk)
